name: Build & Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582

    - name: Build & test custom rule
      run: ./gradlew clean checkstyle-no-private-method-annotation-rule:build checkstyle-no-private-method-annotation-rule:test

    - name: Run demo checkstyle and verify error
      run: |
        set +e
        ./gradlew demo:checkstyleMain > checkstyle.log 2>&1
        exit_code=$?
        grep "10:5: Annotation 'MyAnnotation' is not allowed on private methods \[NoPrivateAnnotatedMethod\]" checkstyle.log
        grep_exit_code=$?
        if [ $exit_code -ne 1 ]; then
          echo "Expected exit code 1, got $exit_code"
          exit 1
        fi
        if [ $grep_exit_code -ne 0 ]; then
          echo "Expected error message not found in log"
          exit 1
        fi
        echo "Checkstyle failed as expected and error message found."
      shell: bash
